library(ISLR)
Carseats <- na.omit(Carseats)
summary(Carseats)
sapply(Carseats,is.factor)
reg1 <- lm(Sales ~ US + Urban + Price,data=Carseats)
summary(reg1)
reg2 <- lm(Sales ~ US + Price,data=Carseats)
summary(reg2)
par(mfrow = c(2, 2))
plot(reg2)